# Code generated by protoc-gen-twirp_ruby 1.11.0, DO NOT EDIT.
require 'twirp'

module TestApp
  class HelloWorldService < ::Twirp::Service
    package 'test_app'
    service 'HelloWorld'
    rpc :Hello, TestApp::HelloReq, TestApp::HelloResp, :ruby_method => :hello
  end

  class HelloWorldClient < ::Twirp::Client
    client_for HelloWorldService
  end
end
